makefile test fix attempt

diff --git a/module2_task0/Makefile b/module2_task0/Makefile
--- a/module2_task0/Makefile
+++ b/module2_task0/Makefile
@@ -13,12 +13,18 @@ clean: stop ## Clean awesome-api application and log
 test: ## Test current connection
 	@status=$$(curl -s -o /dev/null -w "%{http_code}\n" http://localhost:9999 || true); \
 	if [ $$status -eq 200 ]; then \
-		curl -s http://localhost:9999/health || true; \
+		response=$$(curl -s http://localhost:9999/health || true); \
+		echo $$response; \
+		if [ "$$response" != "TESTOK" ] && [ "$$response" != "ALIVE" ]; then \
+			echo "Test failed. Unexpected response."; \
+			exit 1; \
+		fi; \
+	elif [ $$status -eq 404 ]; then \
+		echo $$status; \
 	else \
 		echo "Test failed. Application not running or not accessible."; \
 		exit 1; \
 	fi
-
 
 help: ## Display what each command does
 	cat Makefile | grep '##' | tr -d '##' | head -n -1
