test makefile fix

diff --git a/module2_task0/Makefile b/module2_task0/Makefile
--- a/module2_task0/Makefile
+++ b/module2_task0/Makefile
@@ -11,8 +11,14 @@ clean: stop ## Clean awesome-api application and log
 	rm -f awesome-api awesome-api.log
 
 test: ## Test current connection
-	@curl -s -o /dev/null -w "%{http_code}\n" http://localhost:9999 || true
-	@curl -s http://localhost:9999/health || true
+	@status=$$(curl -s -o /dev/null -w "%{http_code}\n" http://localhost:9999 || true); \
+	if [ $$status -eq 200 ]; then \
+		curl -s http://localhost:9999/health || true; \
+	else \
+		echo "Test failed. Application not running or not accessible."; \
+		exit 1; \
+	fi
+
 
 help: ## Display what each command does
 	cat Makefile | grep '##' | tr -d '##' | head -n -1
